---
# tasks file for kube_worker_config
- name: installing docker and iproute-tc
  package: 
    name:
    - docker
    - iproute-tc
    state: present

- name: configuration of yum repository
  yum_repository:
    name: kubernetes
    description: yum repo for k8s
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
  
- name: installation of kubernetes 
  package:
    name:
      - "kubeadm"
      - "kubelet"
      - "kubectl"
    state: present
    disable_excludes: "kubernetes"

- name: enabling docker and kubelet services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kubelet
    - docker
  
- name: copying the content of daemon.json
  copy:
    dest: /etc/docker.daemon.json
    src: daemon.json

- name: restarting the docker service
  service:
    name: docker
    state: restarted
  
- name: copying k8s.conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf

- name: executing the command sysctl
  command: sysctl --system
  
- name: joining to master node
  copy:
    src: /root/token.sh
    dest: /root/token.sh

- name: run the token file to join
  shell: chmod +x /root/token.sh && sh /root/token.sh
  
